libhb/gtk: do not modify stderr struct directly on mingw
Breaks mingw build when using UCRT:

../libhb/hb.c: In function 'redirect_thread_func':
../libhb/hb.c:2314:11: error: 'FILE' {aka 'struct _iobuf'} has no member named '_file'
 2314 |     stderr->_file = pfd[1];
      |           ^~

See:

https://github.com/mingw-w64/mingw-w64/commit/fe226dd9028f3f64bef4b4384edb1ef2c95c15f4