Unbreak non-mingw cross.
Strings in python are immutable and it results in:

Traceback (most recent call last):
  File "make/configure.py", line 1592, in <module>
    action.run()
  File "make/configure.py", line 287, in run
    self._action()
  File "make/configure.py", line 506, in _action
    self.systemf[0] = self.systemf[0].upper()
TypeError: 'str' object does not support item assignment